# QtVoyager funding / commercial licensing
# Personal & non-commercial use is free; commercial use requires a license.
ko_fi: aliammari
custom:
  - "https://ko-fi.com/aliammari"
  - "mailto:ammari.ali.0001@gmail.com?subject=QtVoyager%20commercial%20license"
